# Generated by Django 5.2.17 on 2026-09-24 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('lessons', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Beceri adı')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='accounts.workspace')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('', 'Değerlendirilmedi'), ('not_learned', 'Öğrenilmedi'), ('practicing', 'Çalışılıyor'), ('can_do', 'Yapabiliyor'), ('good', 'İyi'), ('mastered', 'Ustalaştı')], default='', max_length=20, verbose_name='Durum')),
                ('evaluated_on', models.DateField(blank=True, null=True, verbose_name='Değerlendirme tarihi')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='Kısa açıklama')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_assessments', to='students.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('', 'Değerlendirilmedi'), ('not_learned', 'Öğrenilmedi'), ('practicing', 'Çalışılıyor'), ('can_do', 'Yapabiliyor'), ('good', 'İyi'), ('mastered', 'Ustalaştı')], max_length=20, verbose_name='Durum')),
                ('evaluated_on', models.DateField(verbose_name='Değerlendirme tarihi')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='Kısa açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_history', to='lessons.lesson')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='students.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_history', to='students.student')),
            ],
            options={
                'ordering': ['-evaluated_on', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_workspace_skill'),
        ),
        migrations.AddConstraint(
            model_name='studentskill',
            constraint=models.UniqueConstraint(fields=('student', 'skill'), name='unique_student_skill'),
        ),
    ]
