# Generated by Django 5.2.17 on 2026-09-24 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_skill_studentskill_studentskillhistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Başlangıç'), ('basic', 'Temel'), ('intermediate', 'Orta'), ('advanced', 'İleri')], max_length=20, verbose_name='Seviye')),
                ('effective_on', models.DateField(verbose_name='Geçerlilik tarihi')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_history', to='students.student')),
            ],
            options={
                'ordering': ['-effective_on', '-created_at'],
            },
        ),
    ]
