# Generated by Django 5.2.17 on 2026-09-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentlevelhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSafetyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_name_ciphertext', models.TextField(blank=True)),
                ('emergency_contact_phone_ciphertext', models.TextField(blank=True)),
                ('safety_note_ciphertext', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_profile', to='students.student')),
            ],
        ),
    ]
