# Generated by Django 5.2.17 on 2026-10-04

import django.utils.timezone
from django.db import migrations, models


def enable_postgresql_rls(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('ALTER TABLE accounts_auththrottle ENABLE ROW LEVEL SECURITY')


def disable_postgresql_rls(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('ALTER TABLE accounts_auththrottle DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('key_hash', models.CharField(max_length=64)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('window_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['blocked_until'], name='accounts_au_blocked_01d070_idx')],
                'constraints': [models.UniqueConstraint(fields=('action', 'key_hash'), name='unique_auth_throttle_key')],
            },
        ),
        migrations.RunPython(enable_postgresql_rls, disable_postgresql_rls),
    ]
