# Generated by Django 5.2.17 on 2026-09-24 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(verbose_name='Başlangıç')),
                ('ends_at', models.DateTimeField(verbose_name='Bitiş')),
                ('lesson_type', models.CharField(choices=[('one_to_one', 'Birebir ders'), ('group', 'Grup dersi')], max_length=20, verbose_name='Ders türü')),
                ('status', models.CharField(choices=[('planned', 'Planlandı'), ('completed', 'Tamamlandı'), ('no_show', 'Öğrenci gelmedi'), ('cancelled', 'İptal edildi')], default='planned', max_length=20, verbose_name='Durum')),
                ('instructor_note', models.TextField(blank=True, verbose_name='Eğitmen notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='accounts.workspace')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Not')),
                ('noted_on', models.DateField(verbose_name='Not tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='lessons.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_notes', to='students.student')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_notes', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-noted_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Lokasyon adı')),
                ('address', models.CharField(blank=True, max_length=240, verbose_name='Adres')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='accounts.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='lessons.location'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('attended', 'Katıldı'), ('absent', 'Gelmedi'), ('excused', 'İzinli'), ('cancelled', 'Ders iptal')], max_length=20, verbose_name='Katılım')),
                ('note', models.TextField(blank=True, verbose_name='Ders notu')),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='students.student')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='lessons.lesson')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lesson', 'student'), name='unique_lesson_student')],
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['workspace', 'starts_at'], name='lessons_les_workspa_e5e600_idx'),
        ),
    ]
